import { int, float, json, mediumtext, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  negativeKeywords: json("negativeKeywords").$type<string[]>(),
  theme: mysqlEnum("theme", ["light", "dark", "system"]).default("light").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Projects — multi-project container for organizing content, ICP, brand voice, etc.
 */
export const projects = mysqlTable("projects", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  color: varchar("color", { length: 32 }).default("#6366f1").notNull(),
  domain: varchar("domain", { length: 512 }),
  description: text("description"),
  /** ICP: Primary name (e.g., "Medicare-eligible seniors in Florida") */
  icpPrimaryName: varchar("icpPrimaryName", { length: 512 }),
  /** ICP: Who they are — 1-2 sentence description */
  icpWhoTheyAre: text("icpWhoTheyAre"),
  /** ICP: Pain points (max 5 bullet items) */
  icpPains: json("icpPains").$type<string[]>(),
  /** ICP: Goals and motivations (max 5 bullet items) */
  icpGoals: json("icpGoals").$type<string[]>(),
  /** ICP: Common objections (max 5 bullet items) */
  icpObjections: json("icpObjections").$type<string[]>(),
  /** ICP: Decision triggers (max 5 bullet items) */
  icpDecisionTriggers: json("icpDecisionTriggers").$type<string[]>(),
  /** ICP: Trust signals (max 5 bullet items) */
  icpTrustSignals: json("icpTrustSignals").$type<string[]>(),
  /** S3 key for the reference document used by Cross Check feature */
  referenceDocS3Key: varchar("referenceDocS3Key", { length: 1024 }),
  /** Original filename of the reference document for display */
  referenceDocName: varchar("referenceDocName", { length: 512 }),
  /** Character count of the reference document (for display without fetching from S3) */
  referenceDocLength: int("referenceDocLength"),
  /** Full content of the reference document (primary storage — DB is source of truth, S3 is backup) */
  referenceDocContent: mediumtext("referenceDocContent"),
  /** Banned phrases that should never appear in generated content (JSON array of strings) */
  bannedPhrases: json("bannedPhrases").$type<string[]>(),
  /** LLM provider: 'builtin' (default Gemini via Forge) or 'claude' (Anthropic Claude) */
  llmProvider: varchar("llmProvider", { length: 32 }).default("builtin").notNull(),
  /** Claude model to use when llmProvider is 'claude' */
  llmModel: varchar("llmModel", { length: 128 }),
  /** Minimum number of internal links the LLM must include per generated article (0 = no floor) */
  minInternalLinks: int("minInternalLinks").default(3).notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Project = typeof projects.$inferSelect;
export type InsertProject = typeof projects.$inferInsert;

/**
 * Outlines — structured article outlines with sections, generated by AI or manually created.
 */
export const outlines = mysqlTable("outlines", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 512 }).notNull(),
  /** Target keyword for this outline */
  keyword: varchar("keyword", { length: 255 }),
  /** JSON array of outline sections: { heading, subheading?, points?, type: 'h2'|'h3' } */
  sections: json("sections").$type<OutlineSection[]>().notNull(),
  /** Additional generation settings stored as JSON */
  settings: json("settings").$type<OutlineSettings>(),
  status: mysqlEnum("outlineStatus", ["draft", "approved", "generating", "complete"]).default("draft").notNull(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Outline = typeof outlines.$inferSelect;
export type InsertOutline = typeof outlines.$inferInsert;

/**
 * Outline Versions — tracks revision history for outlines, enabling side-by-side diff comparison.
 */
export const outlineVersions = mysqlTable("outline_versions", {
  id: int("id").autoincrement().primaryKey(),
  outlineId: int("outlineId").notNull(),
  versionNumber: int("versionNumber").notNull(),
  label: varchar("label", { length: 255 }).notNull(),
  /** JSON array of sections at this version */
  sections: json("sections").$type<OutlineSection[]>().notNull(),
  /** Optional raw text that was pasted (for original versions) */
  rawText: text("rawText"),
  /** Score at this version (from AI analysis) */
  score: int("score"),
  /** Summary of changes from previous version */
  changeSummary: text("changeSummary"),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type OutlineVersion = typeof outlineVersions.$inferSelect;
export type InsertOutlineVersion = typeof outlineVersions.$inferInsert;

export interface OutlineSection {
  id: string;
  heading: string;
  type: "h2" | "h3";
  points?: string[];
  subSections?: OutlineSection[];
  aiInstructions?: string;
  backgroundColor?: string;
  /** Template type for special rendering (e.g., 'pro-tip', 'summary', 'use-cases', 'coverage-card') */
  templateType?: "pro-tip" | "summary" | "use-cases" | "coverage-card";
  /** Target word count for this section (used in outline review and article generation) */
  targetWordCount?: number;
}

export interface OutlineSettings {
  contentType?: string;
  tone?: string;
  targetWordCount?: number;
  numSections?: number;
  numFaqs?: number;
  additionalInstructions?: string;
  targetLocation?: string;
  targetAudience?: string;
  outputFormat?: "html" | "plaintext";
  manualLinks?: { url: string; anchorText: string }[];
  sitemapUrl?: string;
  sitemapUrls?: string[];
  autoLinkCount?: number;
  /** Secondary keywords / LSI terms to weave into the article */
  secondaryKeywords?: string[];
}

/**
 * Articles — full content pieces generated from outlines or created manually.
 */
export const articles = mysqlTable("articles", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 512 }).notNull(),
  /** Full HTML content of the article */
  content: text("content"),
  /** Plain text excerpt for previews */
  excerpt: text("excerpt"),
  /** Primary target keyword */
  keyword: varchar("keyword", { length: 255 }),
  /** Additional keywords as JSON array */
  keywords: json("keywords").$type<string[]>(),
  /** SEO meta title */
  metaTitle: varchar("metaTitle", { length: 255 }),
  /** SEO meta description */
  metaDescription: text("metaDescription"),
  /** Permalink slug */
  slug: varchar("slug", { length: 512 }),
  /** Word count of the article */
  wordCount: int("wordCount").default(0),
  /** Article status workflow */
  status: mysqlEnum("articleStatus", ["draft", "review", "complete", "published"]).default("draft").notNull(),
  /** Content type: blog, comparison, guide, listicle, etc. */
  contentType: varchar("contentType", { length: 64 }),
  /** Link to the outline used to generate this article */
  outlineId: int("outlineId"),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Article = typeof articles.$inferSelect;
export type InsertArticle = typeof articles.$inferInsert;

/**
 * ICP Profiles — Ideal Customer Profile targeting for content generation.
 */
export const icpProfiles = mysqlTable("icp_profiles", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  /** Target demographics: age range, location, income, education, etc. */
  demographics: json("demographics").$type<ICPDemographics>(),
  /** Pain points the ICP experiences */
  painPoints: json("painPoints").$type<string[]>(),
  /** Goals and motivations */
  goals: json("goals").$type<string[]>(),
  /** Objections or concerns */
  objections: json("objections").$type<string[]>(),
  /** Preferred content formats and channels */
  contentPreferences: json("contentPreferences").$type<string[]>(),
  /** Search behavior: what they search for, how they search */
  searchBehavior: text("searchBehavior"),
  /** Whether this is the default ICP for the project */
  isDefault: int("isDefault").default(0).notNull(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ICPProfile = typeof icpProfiles.$inferSelect;
export type InsertICPProfile = typeof icpProfiles.$inferInsert;

export interface ICPDemographics {
  ageRange?: string;
  location?: string;
  income?: string;
  education?: string;
  occupation?: string;
  other?: string;
}

/**
 * Brand Voices — writing style and tone configuration for content generation.
 * Matches original RankPilot: two-tier tones, perspective, sentence style, avoid list.
 */
export const brandVoices = mysqlTable("brand_voices", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  /** Serialized tone traits: "PRIMARY:Friendly,Professional|SUPPORTING:Empathetic,Calm,Trustworthy" */
  toneTraits: text("toneTraits"),
  /** Writing perspective: first, second, third */
  perspective: varchar("perspective", { length: 32 }).default("second").notNull(),
  /** Sentence style: short, mixed, detailed */
  sentenceStyle: varchar("sentenceStyle", { length: 32 }).default("mixed").notNull(),
  /** 1-3 paragraph sample demonstrating the ideal voice */
  writingStyleSample: text("writingStyleSample"),
  /** Serialized avoid list: "PRESETS:jargon,salesy|CUSTOM:competitor mentions" */
  avoidList: text("avoidList"),
  /** Whether this is the default voice for the project */
  isDefault: int("isDefault").default(0).notNull(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type BrandVoice = typeof brandVoices.$inferSelect;
export type InsertBrandVoice = typeof brandVoices.$inferInsert;

/**
 * CTA Templates — reusable call-to-action blocks for article generation.
 */
export const ctaTemplates = mysqlTable("cta_templates", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  /** The CTA text/HTML content */
  content: text("content").notNull(),
  /** CTA type: inline, banner, sidebar, footer, popup */
  type: varchar("type", { length: 64 }).default("inline").notNull(),
  /** Where in the article to place this CTA */
  placement: varchar("placement", { length: 64 }).default("end").notNull(),
  /** Optional URL the CTA links to */
  url: varchar("url", { length: 1024 }),
  /** Optional button text */
  buttonText: varchar("buttonText", { length: 255 }),
  /** Whether this is the default CTA for the project */
  isDefault: int("isDefault").default(0).notNull(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type CTATemplate = typeof ctaTemplates.$inferSelect;
export type InsertCTATemplate = typeof ctaTemplates.$inferInsert;

/**
 * Sitemaps — parsed XML sitemaps for internal linking during article generation.
 */
export const sitemaps = mysqlTable("sitemaps", {
  id: int("id").autoincrement().primaryKey(),
  /** The sitemap URL (e.g., https://example.com/sitemap.xml) */
  url: varchar("url", { length: 2048 }).notNull(),
  /** JSON array of parsed URLs from the sitemap */
  parsedUrls: json("parsedUrls").$type<SitemapUrl[]>().notNull(),
  /** Number of URLs found in the sitemap */
  urlCount: int("urlCount").default(0).notNull(),
  projectId: int("projectId").notNull(),
  lastParsed: timestamp("lastParsed").defaultNow().notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Sitemap = typeof sitemaps.$inferSelect;
export type InsertSitemap = typeof sitemaps.$inferInsert;

export interface SitemapUrl {
  url: string;
  title?: string;
  lastmod?: string;
}

/**
 * Citation Sources — trusted reference URLs for AI to cite in generated articles.
 */
export const citationSources = mysqlTable("citation_sources", {
  id: int("id").autoincrement().primaryKey(),
  /** Display name (e.g., "Medicare.gov - Official Medicare Information") */
  name: varchar("name", { length: 512 }).notNull(),
  /** Base URL (e.g., "https://www.medicare.gov") */
  url: varchar("url", { length: 2048 }).notNull(),
  /** Optional description of what this source covers */
  description: text("description"),
  /** Optional category (e.g., "Government", "Research", "Industry") */
  category: varchar("category", { length: 128 }),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type CitationSource = typeof citationSources.$inferSelect;
export type InsertCitationSource = typeof citationSources.$inferInsert;

/**
 * GSC Exports — uploaded Google Search Console Excel exports with parsed and categorized keyword data.
 */
export const gscExports = mysqlTable("gsc_exports", {
  id: int("id").autoincrement().primaryKey(),
  /** Original filename of the uploaded Excel file */
  fileName: varchar("fileName", { length: 512 }).notNull(),
  /** Date range from the Filters sheet (e.g., "Last 3 months") */
  dateRange: varchar("dateRange", { length: 128 }),
  /** Total number of queries parsed from the Queries sheet */
  totalQueries: int("totalQueries").default(0).notNull(),
  /** Total number of pages parsed from the Pages sheet */
  totalPages: int("totalPages").default(0).notNull(),
  /** All raw query rows: { query, clicks, impressions, ctr, position }[] */
  queries: json("queries").$type<GscQueryRow[]>().notNull(),
  /** All raw page rows: { page, clicks, impressions, ctr, position }[] */
  pages: json("pages").$type<GscPageRow[]>().notNull(),
  /** Chart/trend data: { date, clicks, impressions, ctr, position }[] */
  chartData: json("chartData").$type<GscChartRow[]>(),
  /** Near-jump keywords (pos 5–30 depending on threshold) — pre-computed */
  nearJumpKeywords: json("nearJumpKeywords").$type<GscQueryRow[]>(),
  /** High impression / low CTR keywords — pre-computed */
  highImpressionLowCtr: json("highImpressionLowCtr").$type<GscQueryRow[]>(),
  /** Quick win keywords — pre-computed */
  quickWinKeywords: json("quickWinKeywords").$type<GscQueryRow[]>(),
  /** Zero-click pages — pre-computed */
  zeroClickPages: json("zeroClickPages").$type<GscPageRow[]>(),
  /** Cannibalization groups — pre-computed */
  cannibalizationGroups: json("cannibalizationGroups").$type<GscCannibalizationGroup[]>(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type GscExport = typeof gscExports.$inferSelect;
export type InsertGscExport = typeof gscExports.$inferInsert;

export interface GscQueryRow {
  query: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
}

export interface GscPageRow {
  page: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
}

export interface GscChartRow {
  date: string;
  clicks: number;
  impressions: number;
  ctr: number;
  position: number;
}

export interface GscCannibalizationGroup {
  /** The shared keyword stem / topic */
  topic: string;
  /** Queries that overlap on this topic */
  queries: GscQueryRow[];
}

/**
 * App Users — custom email/password authentication (independent of Manus OAuth).
 * This table stores users who can log into RankPilot with their own credentials.
 */
export const appUsers = mysqlTable("app_users", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  email: varchar("email", { length: 320 }).notNull().unique(),
  /** bcrypt hash of the user's password */
  passwordHash: varchar("passwordHash", { length: 255 }).notNull(),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  /** Whether the account is active (admins can disable accounts) */
  isActive: int("isActive").default(1).notNull(),
  /** Whether the user must change their password on next login */
  mustChangePassword: int("mustChangePassword").default(0).notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastLoginAt: timestamp("lastLoginAt"),
  /** User's preferred theme: light, dark, or system */
  theme: mysqlEnum("theme", ["light", "dark", "system"]).default("light").notNull(),
});

export type AppUser = typeof appUsers.$inferSelect;
export type InsertAppUser = typeof appUsers.$inferInsert;

/**
 * Scheduled Jobs — automated content generation jobs that run on a schedule.
 * Supports keyword queue mode (pre-loaded keywords) and AI-suggested mode.
 */
export const scheduledJobs = mysqlTable("scheduled_jobs", {
  id: int("id").autoincrement().primaryKey(),
  /** Human-readable job name (e.g., "Weekly Medicare Blog Posts") */
  name: varchar("name", { length: 255 }).notNull(),
  /** Keyword source: 'queue' (pick from keyword queue) or 'ai' (AI suggests next topic) */
  keywordSource: mysqlEnum("keywordSource", ["queue", "ai"]).default("queue").notNull(),
  /** Frequency: daily, weekly, monthly */
  frequency: mysqlEnum("frequency", ["daily", "weekly", "monthly"]).default("weekly").notNull(),
  /** Day of week for weekly (0=Sun..6=Sat), day of month for monthly (1-31) */
  dayOfWeek: int("dayOfWeek"),
  dayOfMonth: int("dayOfMonth"),
  /** Hour of day to run (0-23, UTC) */
  hourUtc: int("hourUtc").default(8).notNull(),
  /** Article generation settings */
  articleSettings: json("articleSettings").$type<ScheduledJobSettings>().notNull(),
  /** Job status */
  status: mysqlEnum("jobStatus", ["active", "paused", "completed"]).default("active").notNull(),
  /** Total articles generated by this job */
  totalGenerated: int("totalGenerated").default(0).notNull(),
  /** Last successful run timestamp */
  lastRunAt: timestamp("lastRunAt"),
  /** Next scheduled run timestamp */
  nextRunAt: timestamp("nextRunAt"),
  /** Whether the job is currently executing */
  isRunning: int("isRunning").default(0).notNull(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ScheduledJob = typeof scheduledJobs.$inferSelect;
export type InsertScheduledJob = typeof scheduledJobs.$inferInsert;

export interface ScheduledJobSettings {
  /** Target word count for generated articles */
  targetWordCount?: number;
  /** Number of H2 sections */
  numSections?: number;
  /** Number of FAQ items */
  numFaqs?: number;
  /** Content type: blog, comparison, guide, listicle, etc. */
  contentType?: string;
  /** Output format */
  outputFormat?: "html" | "plaintext";
  /** Brand voice ID to use */
  brandVoiceId?: number;
  /** ICP profile ID to use */
  icpProfileId?: number;
  /** Additional instructions for the AI */
  additionalInstructions?: string;
  /** Target location */
  targetLocation?: string;
  /** Target audience */
  targetAudience?: string;
  /** Secondary keywords */
  secondaryKeywords?: string[];
  /** Auto-link count from sitemap */
  autoLinkCount?: number;
  /** Sitemap URLs for internal linking */
  sitemapUrls?: string[];
  /** Tone: professional, casual, authoritative, conversational, etc. */
  tone?: string;
  /** Whether to run pre-generation web research */
  researchEnabled?: boolean;
  /** Whether to automatically grade and iteratively improve the article after generation */
  autoGradeEnabled?: boolean;
  /** Target grade to reach before stopping iterations (e.g. 'A', 'A-', 'B+') */
  targetGrade?: string;
  /** Maximum number of grade-and-improve iterations (default 2) */
  maxGradeIterations?: number;
  /** Whether to auto-suggest secondary keywords per run (4 related + 2 LSI + 2 long-tail) */
  suggestKeywordsEnabled?: boolean;
  /** Manual internal links to force-include in articles */
  manualLinks?: Array<{ url: string; anchorText: string }>;
}

/**
 * Keyword Queue — ordered list of keywords for scheduled jobs in 'queue' mode.
 * Each keyword is processed in order; once used, it's marked as 'completed'.
 */
export const keywordQueue = mysqlTable("keyword_queue", {
  id: int("id").autoincrement().primaryKey(),
  /** The target keyword */
  keyword: varchar("keyword", { length: 512 }).notNull(),
  /** Optional secondary keywords for this item */
  secondaryKeywords: json("secondaryKeywords").$type<string[]>(),
  /** Position in the queue (lower = processed first) */
  sortOrder: int("sortOrder").default(0).notNull(),
  /** Status: pending, processing, completed, failed */
  status: mysqlEnum("queueStatus", ["pending", "processing", "completed", "failed"]).default("pending").notNull(),
  /** ID of the article generated from this keyword (null if not yet processed) */
  generatedArticleId: int("generatedArticleId"),
  /** Error message if generation failed */
  errorMessage: text("errorMessage"),
  /** When this keyword was processed */
  processedAt: timestamp("processedAt"),
  jobId: int("jobId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type KeywordQueueItem = typeof keywordQueue.$inferSelect;
export type InsertKeywordQueueItem = typeof keywordQueue.$inferInsert;

/**
 * Job Run History — log of each scheduled job execution.
 */
export const jobRunHistory = mysqlTable("job_run_history", {
  id: int("id").autoincrement().primaryKey(),
  /** The keyword used for this run */
  keyword: varchar("keyword", { length: 512 }).notNull(),
  /** How the keyword was sourced */
  keywordSource: mysqlEnum("runKeywordSource", ["queue", "ai"]).default("queue").notNull(),
  /** Run status */
  status: mysqlEnum("runStatus", ["running", "completed", "failed"]).default("running").notNull(),
  /** ID of the generated article (null if failed) */
  articleId: int("articleId"),
  /** ID of the generated outline */
  outlineId: int("outlineId"),
  /** Error message if the run failed */
  errorMessage: text("errorMessage"),
  /** Duration in milliseconds */
  durationMs: int("durationMs"),
  /** When the run started */
  startedAt: timestamp("startedAt").defaultNow().notNull(),
  /** When the run completed */
  completedAt: timestamp("completedAt"),
  jobId: int("jobId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type JobRunHistoryEntry = typeof jobRunHistory.$inferSelect;
export type InsertJobRunHistoryEntry = typeof jobRunHistory.$inferInsert;

/**
 * Scheduler Run Logs — step-level log entries for each job run.
 * Multiple entries per run, forming a timeline of what happened.
 */
export const schedulerRunLogs = mysqlTable("scheduler_run_logs", {
  id: int("id").autoincrement().primaryKey(),
  /** Reference to the job_run_history entry */
  runId: int("runId").notNull(),
  /** Reference to the scheduled job */
  jobId: int("jobId").notNull(),
  /** Pipeline step: keyword_selection, outline, article, grading, em_dash_removal, complete, error */
  step: varchar("step", { length: 64 }).notNull(),
  /** Log level: info, success, warning, error */
  level: varchar("level", { length: 16 }).default("info").notNull(),
  /** Human-readable log message */
  message: varchar("message", { length: 1024 }).notNull(),
  /** Optional metadata (e.g., word count, grade result, iteration number) */
  metadata: json("metadata").$type<Record<string, any>>(),
  /** When this log entry was created */
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});

export type SchedulerRunLog = typeof schedulerRunLogs.$inferSelect;
export type InsertSchedulerRunLog = typeof schedulerRunLogs.$inferInsert;

/**
 * Project Keywords — saved keywords associated with a project for tracking and content planning.
 * Keywords can be added from Keyword Research, manual entry, or CSV/TXT import.
 */
export const projectKeywords = mysqlTable("project_keywords", {
  id: int("id").autoincrement().primaryKey(),
  /** Reference to the parent project */
  projectId: int("projectId").notNull(),
  /** The keyword text */
  keyword: varchar("keyword", { length: 255 }).notNull(),
  /** Monthly search volume */
  volume: int("volume").default(0).notNull(),
  /** Cost per click (USD) */
  cpc: float("cpc").default(0).notNull(),
  /** Raw competition score (0-1) */
  competition: float("competition").default(0).notNull(),
  /** Human-readable competition label */
  competitionLabel: mysqlEnum("competitionLabel", ["Low", "Medium", "High"]).default("Low").notNull(),
  /** Trend direction based on recent search data */
  trendDirection: mysqlEnum("trendDirection", ["rising", "declining", "stable"]).default("stable").notNull(),
  /** 12-month trend data as JSON array of { month, year, value } */
  trendData: json("trendData").$type<{ month: string; year: number; value: number }[]>(),
  /** Keyword difficulty score (0-100), nullable for future use */
  kd: int("kd"),
  /** Current SERP position, nullable for future use */
  position: int("position"),
  /** Calculated priority score (0-100) based on volume, competition, CPC */
  priority: int("priority").default(0).notNull(),
  /** Priority bucket label */
  priorityLabel: mysqlEnum("priorityLabel", ["High", "Med", "Low"]).default("Low").notNull(),
  /** Content status for this keyword */
  status: mysqlEnum("keywordStatus", ["none", "article", "outline"]).default("none").notNull(),
  /** Link to existing article if matched */
  articleId: int("articleId"),
  /** Associated page URL on the site */
  pageUrl: varchar("pageUrl", { length: 1024 }),
  /** Source of the keyword: keyword-research, manual, import */
  source: varchar("source", { length: 64 }).default("manual").notNull(),
  /** Who added this keyword */
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ProjectKeyword = typeof projectKeywords.$inferSelect;
export type InsertProjectKeyword = typeof projectKeywords.$inferInsert;

/**
 * Ideas — AI-generated article ideas saved to projects for content planning.
 * Generated via LLM from a seed keyword with optional content type filters and custom instructions.
 */
export const ideas = mysqlTable("ideas", {
  id: int("id").autoincrement().primaryKey(),
  /** Article title suggestion */
  title: varchar("title", { length: 512 }).notNull(),
  /** Primary target keyword */
  keyword: varchar("keyword", { length: 255 }).notNull(),
  /** Search intent: informational, transactional, local, navigational */
  searchIntent: varchar("searchIntent", { length: 64 }),
  /** Suggested word count range (e.g., "1500-2500") */
  wordCountRange: varchar("wordCountRange", { length: 32 }),
  /** Content angles to cover */
  contentAngles: json("contentAngles").$type<string[]>(),
  /** Target audience description */
  targetAudience: text("targetAudience"),
  /** Ranking potential: high, medium, low */
  rankingPotential: varchar("rankingPotential", { length: 16 }),
  /** Brief description of what the article would cover */
  description: text("description"),
  /** Content types used during generation (comma-separated) */
  contentTypes: varchar("contentTypes", { length: 512 }),
  /** Status: saved, used (converted to article), archived */
  status: mysqlEnum("ideaStatus", ["saved", "used", "archived"]).default("saved").notNull(),
  /** Reference to generated article if this idea was used */
  articleId: int("articleId"),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Idea = typeof ideas.$inferSelect;
export type InsertIdea = typeof ideas.$inferInsert;


/**
 * Pipeline Jobs — tracks each file ingested from the JSON bucket through the auto-generation pipeline.
 */
export const pipelineJobs = mysqlTable("pipeline_jobs", {
  id: int("id").autoincrement().primaryKey(),
  /** External file ID from the JSON bucket */
  fileId: varchar("fileId", { length: 255 }).notNull(),
  /** Original filename from the bucket */
  filename: varchar("filename", { length: 512 }).notNull(),
  /** Pipeline status: pending, generating_outline, generating_article, pending_approval, approved, sent_to_scheduler, rejected, failed */
  status: mysqlEnum("pipelineStatus", [
    "pending",
    "generating_outline",
    "generating_article",
    "pending_approval",
    "approved",
    "sent_to_scheduler",
    "rejected",
    "failed",
  ]).default("pending").notNull(),
  /** Source URL of the competitor article (optional) */
  sourceUrl: varchar("sourceUrl", { length: 1024 }),
  /** Title extracted from the JSON file */
  title: varchar("pipelineTitle", { length: 512 }),
  /** Keyword extracted from the JSON file */
  keyword: varchar("pipelineKeyword", { length: 255 }),
  /** Category extracted from the JSON file */
  category: varchar("pipelineCategory", { length: 128 }),
  /** Snippet/description from the JSON file */
  snippet: text("snippet"),
  /** Reference to the generated idea */
  ideaId: int("ideaId"),
  /** Reference to the generated outline */
  outlineId: int("outlineId"),
  /** Reference to the generated article */
  articleId: int("articleId"),
  /** Error message if the job failed */
  errorMessage: text("errorMessage"),
  /** Project this job belongs to */
  projectId: int("projectId").notNull(),
  /** User who triggered or owns the job */
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  processedAt: timestamp("processedAt"),
});
export type PipelineJob = typeof pipelineJobs.$inferSelect;
export type InsertPipelineJob = typeof pipelineJobs.$inferInsert;

/**
 * Pipeline Settings — per-project configuration for the automated content pipeline.
 */
export const pipelineSettings = mysqlTable("pipeline_settings", {
  id: int("id").autoincrement().primaryKey(),
  /** The URL of the JSON bucket to poll */
  bucketUrl: varchar("bucketUrl", { length: 1024 }).default("https://json-test.abacusai.app").notNull(),
  /** Whether the pipeline is enabled */
  enabled: int("enabled").default(1).notNull(),
  /** Auto-generate outline from ingested idea */
  autoGenerateOutline: int("autoGenerateOutline").default(1).notNull(),
  /** Auto-generate article from outline */
  autoGenerateArticle: int("autoGenerateArticle").default(1).notNull(),
  /** Default word count target for generated articles */
  defaultWordCount: int("defaultWordCount").default(1600),
  /** Default tone/style instructions */
  defaultInstructions: text("defaultInstructions"),
  /** Project this setting belongs to */
  projectId: int("projectId").notNull(),
  /** User who owns this setting */
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});
export type PipelineSettingsRow = typeof pipelineSettings.$inferSelect;
export type InsertPipelineSettings = typeof pipelineSettings.$inferInsert;

/**
 * Pipeline Briefs — AI-generated article briefs from ingested S3 data, awaiting user review/approval.
 */
export const pipelineBriefs = mysqlTable("pipeline_briefs", {
  id: int("id").autoincrement().primaryKey(),
  /** Reference to the pipeline job this brief was generated from */
  pipelineJobId: int("pipelineJobId").notNull(),
  /** AI-suggested article title (editable by user) */
  title: varchar("briefTitle", { length: 512 }).notNull(),
  /** Primary target keyword (editable by user) */
  primaryKeyword: varchar("briefPrimaryKeyword", { length: 255 }).notNull(),
  /** Secondary/semantic keywords as JSON array (editable by user) */
  secondaryKeywords: json("briefSecondaryKeywords").$type<string[]>().notNull(),
  /** Description/main idea of the article (editable by user) */
  description: text("briefDescription").notNull(),
  /** AI-suggested number of hyperlinks for the article */
  suggestedLinkCount: int("suggestedLinkCount").notNull(),
  /** AI-suggested word count for the article */
  suggestedWordCount: int("suggestedWordCount").notNull(),
  /** Review status */
  status: mysqlEnum("briefStatus", ["pending_review", "approved", "rejected"]).default("pending_review").notNull(),
  /** When the brief was approved */
  approvedAt: timestamp("approvedAt"),
  /** JSON tracking which fields the user edited before approving */
  editedFields: json("editedFields").$type<string[]>(),
  /** Project this brief belongs to */
  projectId: int("projectId").notNull(),
  /** User who owns this brief */
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
});
export type PipelineBrief = typeof pipelineBriefs.$inferSelect;
export type InsertPipelineBrief = typeof pipelineBriefs.$inferInsert;
