import { int, json, mysqlEnum, mysqlTable, text, timestamp, varchar } from "drizzle-orm/mysql-core";

/**
 * Core user table backing auth flow.
 */
export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(),
  openId: varchar("openId", { length: 64 }).notNull().unique(),
  name: text("name"),
  email: varchar("email", { length: 320 }),
  loginMethod: varchar("loginMethod", { length: 64 }),
  role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(),
  negativeKeywords: json("negativeKeywords").$type<string[]>(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
  lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;

/**
 * Projects — multi-project container for organizing content, ICP, brand voice, etc.
 */
export const projects = mysqlTable("projects", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  color: varchar("color", { length: 32 }).default("#6366f1").notNull(),
  domain: varchar("domain", { length: 512 }),
  description: text("description"),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Project = typeof projects.$inferSelect;
export type InsertProject = typeof projects.$inferInsert;

/**
 * Outlines — structured article outlines with sections, generated by AI or manually created.
 */
export const outlines = mysqlTable("outlines", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 512 }).notNull(),
  /** Target keyword for this outline */
  keyword: varchar("keyword", { length: 255 }),
  /** JSON array of outline sections: { heading, subheading?, points?, type: 'h2'|'h3' } */
  sections: json("sections").$type<OutlineSection[]>().notNull(),
  /** Additional generation settings stored as JSON */
  settings: json("settings").$type<OutlineSettings>(),
  status: mysqlEnum("outlineStatus", ["draft", "approved", "generating", "complete"]).default("draft").notNull(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Outline = typeof outlines.$inferSelect;
export type InsertOutline = typeof outlines.$inferInsert;

export interface OutlineSection {
  id: string;
  heading: string;
  type: "h2" | "h3";
  points?: string[];
  subSections?: OutlineSection[];
}

export interface OutlineSettings {
  contentType?: string;
  tone?: string;
  targetWordCount?: number;
  numSections?: number;
  numFaqs?: number;
  additionalInstructions?: string;
}

/**
 * Articles — full content pieces generated from outlines or created manually.
 */
export const articles = mysqlTable("articles", {
  id: int("id").autoincrement().primaryKey(),
  title: varchar("title", { length: 512 }).notNull(),
  /** Full HTML content of the article */
  content: text("content"),
  /** Plain text excerpt for previews */
  excerpt: text("excerpt"),
  /** Primary target keyword */
  keyword: varchar("keyword", { length: 255 }),
  /** Additional keywords as JSON array */
  keywords: json("keywords").$type<string[]>(),
  /** SEO meta title */
  metaTitle: varchar("metaTitle", { length: 255 }),
  /** SEO meta description */
  metaDescription: text("metaDescription"),
  /** Permalink slug */
  slug: varchar("slug", { length: 512 }),
  /** Word count of the article */
  wordCount: int("wordCount").default(0),
  /** Article status workflow */
  status: mysqlEnum("articleStatus", ["draft", "review", "complete", "published"]).default("draft").notNull(),
  /** Content type: blog, comparison, guide, listicle, etc. */
  contentType: varchar("contentType", { length: 64 }),
  /** Link to the outline used to generate this article */
  outlineId: int("outlineId"),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type Article = typeof articles.$inferSelect;
export type InsertArticle = typeof articles.$inferInsert;

/**
 * ICP Profiles — Ideal Customer Profile targeting for content generation.
 */
export const icpProfiles = mysqlTable("icp_profiles", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  /** Target demographics: age range, location, income, education, etc. */
  demographics: json("demographics").$type<ICPDemographics>(),
  /** Pain points the ICP experiences */
  painPoints: json("painPoints").$type<string[]>(),
  /** Goals and motivations */
  goals: json("goals").$type<string[]>(),
  /** Objections or concerns */
  objections: json("objections").$type<string[]>(),
  /** Preferred content formats and channels */
  contentPreferences: json("contentPreferences").$type<string[]>(),
  /** Search behavior: what they search for, how they search */
  searchBehavior: text("searchBehavior"),
  /** Whether this is the default ICP for the project */
  isDefault: int("isDefault").default(0).notNull(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type ICPProfile = typeof icpProfiles.$inferSelect;
export type InsertICPProfile = typeof icpProfiles.$inferInsert;

export interface ICPDemographics {
  ageRange?: string;
  location?: string;
  income?: string;
  education?: string;
  occupation?: string;
  other?: string;
}

/**
 * Brand Voices — writing style and tone configuration for content generation.
 */
export const brandVoices = mysqlTable("brand_voices", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  description: text("description"),
  /** Overall tone: professional, conversational, authoritative, friendly, etc. */
  tone: varchar("tone", { length: 128 }),
  /** Writing style guidelines */
  style: text("style"),
  /** Words/phrases to use frequently */
  vocabulary: json("vocabulary").$type<string[]>(),
  /** Words/phrases to avoid */
  avoidWords: json("avoidWords").$type<string[]>(),
  /** Example sentences demonstrating the voice */
  examples: json("examples").$type<string[]>(),
  /** Brand-specific rules (e.g., always capitalize Product Name, never use jargon) */
  rules: json("rules").$type<string[]>(),
  /** Whether this is the default voice for the project */
  isDefault: int("isDefault").default(0).notNull(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type BrandVoice = typeof brandVoices.$inferSelect;
export type InsertBrandVoice = typeof brandVoices.$inferInsert;

/**
 * CTA Templates — reusable call-to-action blocks for article generation.
 */
export const ctaTemplates = mysqlTable("cta_templates", {
  id: int("id").autoincrement().primaryKey(),
  name: varchar("name", { length: 255 }).notNull(),
  /** The CTA text/HTML content */
  content: text("content").notNull(),
  /** CTA type: inline, banner, sidebar, footer, popup */
  type: varchar("type", { length: 64 }).default("inline").notNull(),
  /** Where in the article to place this CTA */
  placement: varchar("placement", { length: 64 }).default("end").notNull(),
  /** Optional URL the CTA links to */
  url: varchar("url", { length: 1024 }),
  /** Optional button text */
  buttonText: varchar("buttonText", { length: 255 }),
  /** Whether this is the default CTA for the project */
  isDefault: int("isDefault").default(0).notNull(),
  projectId: int("projectId").notNull(),
  userId: int("userId").notNull(),
  createdAt: timestamp("createdAt").defaultNow().notNull(),
  updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(),
});

export type CTATemplate = typeof ctaTemplates.$inferSelect;
export type InsertCTATemplate = typeof ctaTemplates.$inferInsert;
